name: Docker Build and Push to AWS ECR Public

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR Public
        run: |
          aws ecr-public get-login-password --region ${{ secrets.ECR_AWS_REGION }} | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image
        run: |
          docker build -t dicksonanyaele_asciigen:latest .

      - name: Tag Docker image for ECR Public with correct tag format
        run: |
          docker tag dicksonanyaele_asciigen:latest public.ecr.aws/${{ secrets.ECR_PUBLIC_ALIAS }}/elitekaycy/dicksonanyaele_asciigen:latest

      - name: Push Docker image to ECR Public
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_PUBLIC_ALIAS }}/elitekaycy/dicksonanyaele_asciigen:latest

